### ISSUE TITLE
Crash if surface is deleted during debounce

### ISSUE THREAD

**Issue by mikelat** [tburrows13/FactorySearch#14]
```
The mod Factory Search (1.11.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event FactorySearch::on_tick (ID 0)
LuaSurface API call when LuaSurface was invalid.
stack traceback:
	[C]: in function '__index'
	__FactorySearch__/scripts/search.lua:498: in function 'blocking_search'
	__FactorySearch__/scripts/search.lua:589: in function <__FactorySearch__/scripts/search.lua:581>
```

To reproduce, sandbox and create a new surface. Initate a search **(on all surfaces)** and then during the debounce quickly delete the surface. Error appears.

This happens frequently in mods like SE where it's constantly moving space ships around which are creating/deleting surfaces constantly.

**Comment by tburrows13** [comment]
Fixed in v1.11.1. Sorry for waiting so long!
