### ISSUE TITLE
Feature Request: Set zoom level

### ISSUE THREAD

**Issue by utdrmac** [tburrows13/FactorySearch#2]
I can't seem to find any way to change the zoom level when I click on search results. Can you please add this as a mod option?

**Comment by tburrows13** [comment]
Hey @utdrmac, that could be added. Out of interest, why do you want to change it and what do you think it should be moved to?

**Comment by utdrmac** [comment]
I'm using this mod on my Space Exploration map. The map is huge. When I search for something, it zooms in so close, I can't tell where on the map I am and what's going on around. Some people probably like being zoomed in; others don't. Which is why I thought a config setting would be best.

**Comment by tburrows13** [comment]
Implemented in v1.8.0 :)

**Comment by utdrmac** [comment]
I'll check it out. Thanks! Great mod, especially for the megabases and Space Exploration mod.
