### ISSUE TITLE
Just another project for you to draw inspiration from

### ISSUE THREAD

**Issue by Zomis** [tburrows13/FactorySearch#5]
Hi there!

I haven't tried your mod yet but it looks similar to a mod I have been working on. Unfortunately I don't play any Factorio these days so therefore I also stopped developing my mod.

You can find the mod at https://github.com/Zomis/FactorioMods/tree/search-engine/search-engine_0.0.1

I'd be happy to assist if you have any questions. I might also have a few ideas and suggestions once I get back to playing Factorio and try your mod out.

You can reach me on Discord at Zomis#7085 if you want any direct contact.

**Comment by tburrows13** [comment]
Ref #6 #8 :)

**Comment by Zomis** [comment]
@tburrows13 Just so that you don't miss out: This issue was originally referring to my search mod, which is here: https://github.com/Zomis/FactorioMods/tree/main/search-engine_0.0.1

The Foofle plugin (which the other issues refer to) is something completely different.
