### ISSUE TITLE
The Chinese translation has been updated, please update it as soon as possible in the next release

### ISSUE THREAD

**Issue by PlexPt** [tburrows13/FactorySearch#7]
The Chinese translation has been updated, please update it as soon as possible in the next release

**Comment by tburrows13** [comment]
Hello,
Unfortunately the crowdin integration is currently broken so translations are no longer being synced between crowdin and github (https://github.com/dima74/factorio-mods-localization/issues/16). I don’t know when this will be fixed. For the time being, feel free to send me any .cfc files and I’ll add them manually, or make a pull request :)

**Comment by PlexPt** [comment]
Can you handle it manually?

**Comment by tburrows13** [comment]
By copy-pasting from crowdin, yes. But not sure when I'll get around to it.

**Comment by tburrows13** [comment]
Never mind, I can easily export the while file at once, so I'll include this file in the next release under `zh-CN` (GitHub requires that I add '.txt' to the end of the filename for uploading here).
[FactorySearch.cfg.txt](https://github.com/tburrows13/FactorySearch/files/10374489/FactorySearch.cfg.txt)

**Comment by tburrows13** [comment]
Added in v1.10.8.
